# permissions for end users to edit commits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commit-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - commits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - commits/status
  verbs:
  - get
