# permissions for end users to view commits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commit-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - commits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - commits/status
  verbs:
  - get
