# permissions for end users to view createsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: createsubscription-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - createsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - createsubscriptions/status
  verbs:
  - get
