# permissions for end users to edit editconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: editconfig-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs/status
  verbs:
  - get
