# permissions for end users to view editconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: editconfig-viewer-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs/status
  verbs:
  - get
