# permissions for end users to edit establishsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: establishsubscription-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - establishsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - establishsubscriptions/status
  verbs:
  - get
