# permissions for end users to view gets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - gets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - gets/status
  verbs:
  - get
