# permissions for end users to edit gets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - gets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - gets/status
  verbs:
  - get
