# permissions for end users to view getconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: getconfig-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - getconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - getconfigs/status
  verbs:
  - get
