# permissions for end users to view mountpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mountpoint-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - mountpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - mountpoints/status
  verbs:
  - get
