# permissions for end users to edit mountpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mountpoint-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - mountpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - mountpoints/status
  verbs:
  - get
