
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - commits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - commits/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - commits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - createsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - createsubscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - createsubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - editconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - establishsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - establishsubscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - establishsubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - getconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - getconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - getconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - gets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - gets/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - gets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - locks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - locks/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - locks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - mountpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - mountpoints/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - mountpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - rpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - rpcs/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - rpcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks/finalizers
  verbs:
  - update
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks/status
  verbs:
  - get
  - patch
  - update
