# permissions for end users to view rpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpc-viewer-role
rules:
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - rpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.openshift-telco.io
  resources:
  - rpcs/status
  verbs:
  - get
