# permissions for end users to edit unlocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unlock-editor-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks/status
  verbs:
  - get
