# permissions for end users to view unlocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unlock-viewer-role
rules:
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netconf.adetalhouet.io
  resources:
  - unlocks/status
  verbs:
  - get
