apiVersion: netconf.adetalhouet.io/v1
kind: Notification
metadata:
  name: netconf-notifications
spec:
  mountPoint: csr1kv-mountpoint
  createSubscription:
    - stream: "NETCONF"
      name: default-netconf-subscription
  establishSubscription:
    - name: telemetry-events
      xml: |-
        <establish-subscription
            xmlns="urn:ietf:params:xml:ns:yang:ietf-event-notifications"
            xmlns:yp="urn:ietf:params:xml:ns:yang:ietf-yang-push">
          <stream>yp:yang-push</stream>
          <yp:xpath-filter>/mdt-oper:mdt-oper-data/mdt-subscriptions</yp:xpath-filter>
          <yp:period>1000</yp:period>
        </establish-subscription>
    - name: bgp-events
      xml: |-
        <establish-subscription
            xmlns="urn:ietf:params:xml:ns:yang:ietf-event-notifications"
            xmlns:yp="urn:ietf:params:xml:ns:yang:ietf-yang-push">
           <stream>yp:yang-push</stream>
           <yp:xpath-filter>/bgp-ios-xe-oper:bgp-state-data/neighbors</yp:xpath-filter>
           <yp:period>1000</yp:period>
        </establish-subscription>