apiVersion: netconf.adetalhouet.io/v1
kind: EditConfig
metadata:
  name: edit-config-change-hostname
  namespace: default
spec:
  mountPoint: csr1kv-mountpoint
  operation: merge
  target: candidate
  xml: |-
    <netconf-yang xmlns="http://cisco.com/yang/cisco-self-mgmt">
      <cisco-ia xmlns="http://cisco.com/yang/cisco-ia">
        <snmp-trap-control>
          <trap-list>
            <trap-oid>1.3.6.1.4.1.9.9.41.2.0.1</trap-oid>
          </trap-list>
          <trap-list>
            <trap-oid>1.3.6.1.6.3.1.1.5.3</trap-oid>
          </trap-list>
          <trap-list>
            <trap-oid>1.3.6.1.6.3.1.1.5.4</trap-oid>
          </trap-list>
        </snmp-trap-control>
      </cisco-ia>
    </netconf-yang>